ALTER TABLE `audit_logs`
  MODIFY `action` ENUM(
    'COMPANY_STATUS_UPDATED',
    'COMPANY_LICENSE_UPDATED',
    'COMPANY_PLAN_UPDATED',
    'COMPANY_IMPERSONATION_STARTED',
    'COMPANY_IMPERSONATION_ENDED',
    'SUPPORT_ACTION_EXECUTED'
  ) NOT NULL;
